### ISSUE TITLE
[REVIEW]: StateSpaceModels.jl: a Julia Package for Time-Series Analysis in a State-Space Framework

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#28]
**Submitting author:** @raphaelsaavedra (<a href="http://orcid.org/0000-0003-0095-4114">Raphael Saavedra</a>)
**Repository:** <a href="https://github.com/LAMPSPUC/StateSpaceModels.jl/" target ="_blank">https://github.com/LAMPSPUC/StateSpaceModels.jl/</a>
**Editor:** @ranjanan
**Reviewer:** @dehann, @mschauer
**Archive:** Pending

## Status

[![status](https://proceedings.juliacon.org/papers/bb5fbbdb5e7888d4d980239719fc98bd/status.svg)](https://proceedings.juliacon.org/papers/bb5fbbdb5e7888d4d980239719fc98bd)

Status badge code:

```
HTML: <a href="https://submissions.juliacon.org/papers/bb5fbbdb5e7888d4d980239719fc98bd"><img src="https://submissions.juliacon.org/papers/bb5fbbdb5e7888d4d980239719fc98bd/status.svg"></a>
Markdown: [![status](https://submissions.juliacon.org/papers/bb5fbbdb5e7888d4d980239719fc98bd/status.svg)](https://submissions.juliacon.org/papers/bb5fbbdb5e7888d4d980239719fc98bd)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/LAMPSPUC/StateSpaceModels.jl/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dehann & @mschauer, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/JuliaCon/proceedings-reviews/invitations

The reviewer guidelines are available here: https://proceedings.juliacon.org/guide/reviewers. Any questions/concerns please let @matbesancon know.

✨ **Please try and complete your review in the next two weeks** ✨

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/LAMPSPUC/StateSpaceModels.jl/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Authorship:** Has the submitting author (@raphaelsaavedra) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format

- [x] **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [x] **Page limit:** Is the page limit for full papers respected by the submitted document?

### Content

- [ ] **Context:** is the scientific context motivating the work correctly presented?
- [ ] **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
- [ ] **Results:** are the results presented and compared to approaches with similar goals?

### Conflict of interest

- [ ] As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/LAMPSPUC/StateSpaceModels.jl/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Authorship:** Has the submitting author (@raphaelsaavedra) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format

- [ ] **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [ ] **Page limit:** Is the page limit for full papers respected by the submitted document?

### Content

- [ ] **Context:** is the scientific context motivating the work correctly presented?
- [ ] **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
- [ ] **Results:** are the results presented and compared to approaches with similar goals?

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @dehann, @mschauer it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/JuliaCon/proceedings-review) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/JuliaCon/proceedings-review:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00028/jcon.00028/10.21105.jcon.00028.pdf)

**Comment by matbesancon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.18637/jss.v078.i10 is OK

MISSING DOIs

- https://doi.org/10.1137/141000671 may be missing for title: Julia: A fresh approach to numerical computing
- https://doi.org/10.1093/acprof:oso/9780199641178.001.0001 may be missing for title: Time Series Analysis by State Space Methods
- https://doi.org/10.1109/proc.1965.4237 may be missing for title: Linear System Theory: The State Space Approach
- https://doi.org/10.1109/9780470544334.ch9 may be missing for title: A new approach to linear filtering and prediction problems
- https://doi.org/10.21105/joss.00615 may be missing for title: Optim: A mathematical optimization package for Julia
- https://doi.org/10.17771/pucrio.irr.33804 may be missing for title: Simulating Low and High-Frequency Energy Demand Scenarios in a Unified Framework–Part I: Low-Frequency Simulation

INVALID DOIs

- None
```

**Comment by matbesancon** [comment]
@raphaelsaavedra check the references to update above

**Comment by raphaelsaavedra** [comment]
@matbesancon Thanks! I have included the suggested DOIs, except for "A new approach to linear filtering and prediction problems". I included what I believe is the correct DOI, 10.1115/1.3662552. The updated version is already in the master, do I need to make a new release?

**Comment by matbesancon** [comment]
No I don't think it is necessary now

**Comment by matbesancon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1137/141000671 is OK
- 10.1093/acprof:oso/9780199641178.001.0001 is OK
- 10.1109/proc.1965.4237 is OK
- 10.18637/jss.v078.i10 is OK
- 10.1115/1.3662552 is OK
- 10.21105/joss.00615 is OK
- 10.17771/PUCRio.IRR.33804 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by raphaelsaavedra** [comment]
@matbesancon are we allowed to upload a preprint of the juliacon paper on arxiv using a different template?

**Comment by matbesancon** [comment]
yes

**Comment by matbesancon** [comment]
ping @dehann, @mschauer to continue the review

**Comment by mschauer** [comment]
Nice to meet you. So I should start stating that I share some interest in this topic, see https://github.com/mschauer/Kalman.jl This should be manageable according to PNAS criteria. Actually, my package is somewhat opinionated and small, so you would *expect* a different package to be the go-to package for this topic.

**Comment by mschauer** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by mschauer** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00028/jcon.00028/10.21105.jcon.00028.pdf)

**Comment by raphaelsaavedra** [comment]
@mschauer thanks for taking your time! I should warn you that we have just released a significant performance update in v0.2.3. From what I've seen in the checklist, you have already installed the package, so you might want to update it :)

**Comment by matbesancon** [comment]
ping @dehann, @mschauer to continue the review :)

**Comment by mschauer** [comment]
Thanks for keeping it up, this is up next.

**Comment by mschauer** [comment]
Dear authors,

I have some feedback regarding the design. Some of your implementation choices appear not very idiomatic to me, but you might have good reasons for them. On the other hand, this might be helpful feedback otherwise.

Let's start looking at 
```julia
struct StateSpaceModel
    y::Matrix{Float64} # observations
    Z::Array{Float64, 3} # observation matrix
    T::Matrix{Float64} # state matrix
    R::Matrix{Float64} # state error matrix
    dim::StateSpaceDimensions
    missing_observations::Vector{Int}
    mode::String
end
```
The first thing to notice is that you restrict your users basically throughout to `Float64` matrices of type `Array`. What about embedded systems with `Float32` accuracy? What if their filtering problems are large (and can only be handeled with say banded or block-diagonal matrices? What about static arrays (might be helpful in realtime applications?) 
At some places you seem to have it right,
```
function big_update_K!(K::AbstractMatrix{Typ}, P_Ztransp_invF::AbstractVector{Typ}, T::AbstractMatrix{Typ}, t::Int) where Typ <: AbstractFloat
    @inbounds @views K[:, t] = T * P_Ztransp_invF
    return
end
```
tolerates a range of different inputs. This flexibility in input (container and value-) types is also important for interaction with other packages, e.g. if you want to replace maximum-likelihood estimation by an MCMC method.

Another issue: Does your package support the online application of the filtering algorithm? The Kalman filter is a filter, after all... You mention the focus on time-series applications, but in the end, all the implementations, even the square root filter, are there (you wrote them), it would be nice to make them available in a more generic fashion.

**Comment by raphaelsaavedra** [comment]
Hello @mschauer, thank you for taking your time to do this review.

Regarding the generality of the `StateSpaceModel` structure, we believe you are absolutely right. The package would certainly benefit from allowing a wider range of types. In fact, we already do this inside the code, as you pointed out. We will try to address this point as soon as possible, as it seems like a simple change, at least in terms of allowing other Float types.

With respect to your enquiry about the online application: this is indeed something that we do not allow at the moment. We do have a function called `kfas` that runs the filtering and smoothing steps, but we should definitely allow users to call only the filter if they so desire. We will make filtering available so that online applications can become a possibility. This should also be a simple change.

Once again, thank you for your valuable feedback. We will make the changes and comment here once they are done.

**Comment by raphaelsaavedra** [comment]
Hello @mschauer,

@guilhermebodin and I have discussed and addressed some of your concerns. We have modified the package to allow any float accuracy within the model definition and the filters (https://github.com/LAMPSPUC/StateSpaceModels.jl/pull/101).

With respect to the online application of the filter, after some discussion we have decided not to implement it in the current form of the package. Within our package, the filter data (state information, covariances, Kalman gain etc.) are kept in memory and saved in their full form (all time periods). We do this to allow for studies that can be pertinent within the context of time series analysis. In order to make an online implementation of the filter, we would have to create new filter functions and structures from scratch. While we believe there is definitely value in doing that, we think this might be outside of the current scope of our package, which is mainly focused in time series. This might end up motivating a new package that can deal with online filtering applications.

As an unrelated note, we have also implemented statistical diagnostics to evaluate the model specification and estimation (https://github.com/LAMPSPUC/StateSpaceModels.jl/pull/100).

Thank you for the feedback and do not hesitate to comment again if you have further observations.

**Comment by mschauer** [comment]
Hi, this is a good change.
Can you relax to `Real` in `struct SquareRootFilter{T <: AbstractFloat}` as `AbstractFloat` is to narrow, e.g. dual numbers are only `Real`? Then you can also remove all `<: AbstractFloat` in function definitions as
```
function univariate_smoother(model::StateSpaceModel{Typ}, kfilter::UnivariateKalmanFilter{Typ}) where Typ <: AbstractFloat
``` 
it is enough to contain in one place (the struct itself).
I am looking at the estimation next.

**Comment by raphaelsaavedra** [comment]
We agree this makes sense and it has been changed in https://github.com/LAMPSPUC/StateSpaceModels.jl/pull/107.

**Comment by raphaelsaavedra** [comment]
Hi @matbesancon, I hope you don't mind if I bump this thread since there hasn't been any progress since October.

One of the reviewers hasn't shown up after 8 months, how should we proceed? Is it possible to find another reviewer?

**Comment by dehann** [comment]
HI Sorry, i have the review just forgot to upload.  My bad sorry.  Will do it as soon as possible

**Comment by dehann** [comment]
Dear Authors,

i liked the paper as well as the aim of the package.  I understand the package as standardizing linearized state-space models for JuliaLang, and found the structure familiar from existing literature.  I did have a little trouble switching to the nomenclature in the paper, but that is not serious.

Specific comments:
- p1.,right column (r.) second paragraph (g.2), this you can drop or rephrase the sentence "Furthermore, some have not been updated for a long time and are not functional in Julia1.0." 
- Sec. 3.1.1 perhaps give a bit more detail about "stochastic level component" -- perhaps an example of something one try estimate in the wild.  E.g. estimating the temperature of object without a direct measurement, etc.
- Sec. 3.1.2 Relate slope term directly to eq. 3 - 7.
- Sec. 3.1.3, assuming you mean seasonality in weather sense?  Perhaps just elaborate a little more.
- Section 4, g.1 common literature in state estimation has measurement noise matrix as `R`.  
- Sec 4.1, 4.2, please clarify meaning of "derive" do you perhaps mean "predict"?
- Sec 4.2, clarify use of predict and update cycles, e.g. can you do multiple predictions and then a measurement, or can you do multiple measurements at current value?
- Sec. 6.1, g.1 "well-known" ... perhaps add a reference.
- g.2, "we can analyzed the individual" -> "we can analyze the individual...".
- Sec 6.2, by quantiles, you likely mean 95% the same as 2 sigma since all Gaussian beliefs, not in the sense that multiple filters are running or some other output conversion is done to arrive at quantiles.
- Consider adding a reference to the plotting library used (likely one from Julia :-)

Great, and sorry again for not uploading sooner!

**Comment by raphaelsaavedra** [comment]
Hi @dehann, thank you for your feedback.

Please find below my answers to your comments:

* Regarding the notation of the noise matrix: we have tried to adhere as much as possible to the notation of Durbin & Koopman's book, which was our main reference in this work. In this case, `R` is already reserved for the matrix multiplying the measurement errors.
* By "derive" I mean simply "compute". We have changed it to compute to make it clearer.
* We apologize but your comment regarding Sec. 4.2 wasn't clear to us. In Sec. 4.2, we discuss the estimation procedure and state that we are trying to estimate the error covariances by maximising the likelihood. Since the likelihood is a product of the filter, we need to run the filter at each step of the optimisation procedure until we attain optimality.
* Thank you for pointing out that a reference was missing. We have added the following reference: Helmut Lütkepohl and Fang Xu. The role of the log transformation in forecasting economic variables. Empirical Economics, 42(3):619–638, 2012. 
* By quantiles, we mean actual quantiles of the simulated scenarios. Please note that we have separate functions for forecasting and simulating. When forecasting, the confidence intervals are indeed computed based on the variances as you mentioned. However, when simulating, errors are randomly sampled from their estimated distributions at each step and each scenario has temporal dependency so that they are coherent. Therefore, it is a slightly different procedure and quantiles are computed rather than confidence intervals.
* I would love to add a citation to the plotting library but there is no Plots.jl paper. I could just reference the repository but listing the correct authors is tricky.

Your other suggestions that weren't explicitly addressed above were implemented in the paper.

Furthermore, please note that since the initial pdf was generated, we have added a new section regarding basic statistical diagnostics.

We hope you're satisfied with the new version. If you require any further changes, do not hesitate to ask 🙂

**Comment by raphaelsaavedra** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00028/jcon.00028/10.21105.jcon.00028.pdf)

**Comment by raphaelsaavedra** [comment]
PS: please remember to tick the boxes in the first post according to your impressions :)

**Comment by dehann** [comment]
Done thanks, one more suggestion is to add links to the demo data in the Docs too (already in Readme).

**Comment by raphaelsaavedra** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00028/jcon.00028/10.21105.jcon.00028.pdf)

**Comment by raphaelsaavedra** [comment]
Thanks for the suggestion. We have added reference [14] to the repo in the Applications section, where we mention that the code and data for examples can be found in the `examples` folder.

**Comment by matbesancon** [comment]
Hi @mschauer, we had some delays on the JuliaCon  proceedings handling, would you be ok with continuing this review?

**Comment by vchuravy** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by vchuravy** [comment]
@whedon remind @mschauer in 5 days

**Comment by whedon** [comment]
Reminder set for @mschauer in 5 days

**Comment by whedon** [comment]
:wave: @mschauer, please update us on how your review is going.

**Comment by raphaelsaavedra** [comment]
Any updates here? I see the proceedings are already out (https://proceedings.juliacon.org/).

**Comment by matbesancon** [comment]
Hi @raphaelsaavedra, sorry for the delays we experienced

**Comment by matbesancon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #28 with the following error: 

 Can't find any papers to compile :-(

**Comment by raphaelsaavedra** [comment]
Hi, since the submission, we have made a significant refactor of the package. As a result, we removed the paper from the master, as it had some outdated API documentation. I could perhaps open a branch using an old version and point whedon to it?

**Comment by matbesancon** [comment]
Do you have the paper on a special branch? What I would suggest is:
1. get your paper on the repo and compiling
2. if you did some changes, we will run it by reviewers
3. publish
4. profit

**Comment by matbesancon** [comment]
yes that would work. Also, update the paper to reflect the current package state :)

**Comment by raphaelsaavedra** [comment]
@whedon generate pdf from branch paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00028/jcon.00028/10.21105.jcon.00028.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00028/jcon.00028/10.21105.jcon.00028.pdf) :page_facing_up: :point_left:

**Comment by mschauer** [comment]
Hi, thank you for pointing out the new version, I can see that the package has been redesigned and matured substantially. Now this is a package I can see having a niche in the ecosystem. I am in particular happy about https://github.com/LAMPSPUC/StateSpaceModels.jl/commit/38685eeb9a714dca52a23a6968ad6f4511804597, the introduction of https://github.com/LAMPSPUC/StateSpaceModels.jl/blob/master/src/systems.jl and https://github.com/LAMPSPUC/StateSpaceModels.jl/pull/174, very much in line with our first discussions about your design. I support writing about this modern StateSpaceModels.jl, reflecting the clean new design (no need to preserve the older approaches and the older paper) and then wrapping this up

**Comment by matbesancon** [comment]
Thanks @mschauer!
@raphaelsaavedra let us know when you went through the round of modifications you wanted

**Comment by matbesancon** [comment]
I'm adding "author action required" for now

**Comment by matbesancon** [comment]
ping @raphaelsaavedra it would be good to move on this one

**Comment by matbesancon** [comment]
Thanks for your answer. As highlighted before, the package is now in a much more interesting and feature-complete state (no pun intended). These changes add value to the proceeding and should be reflected there.

There is no blocking point to finish this within a month, I just wanted to know whether to wait or not, there is substantial work that went in this from different sides and it would be sad to throw that away now that the bulk of the work is done.

I will let the author action required to reflect the changes in the proceeding

**Comment by matbesancon** [comment]
@whedon assign @ranjanan as editor

**Comment by luraess** [comment]
Dear author @raphaelsaavedra , we are in the process of resuming the stalled JuliaCon reviews. If you are still interested in getting your work published, please start addressing the author-action-required items within the coming 3 weeks. If no action is taken within the coming 3 weeks, we will close the submission. Thank you for your understanding.

**Comment by lucaferranti** [comment]
@editorialbot reject
