### ISSUE TITLE
[PRE REVIEW]: Designing Machine Learning Pipeline Toolkit for AutoML Surrogate Modeling Optimization

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#88]
**Submitting author:** @ppalmes (<a href="http://orcid.org/0000-0002-3145-6356">Paulito Palmes</a>)
**Repository:** <a href="https://github.com/IBM/AutoMLPipeline.jl" target ="_blank">https://github.com/IBM/AutoMLPipeline.jl</a>
**Version:** 
**Editor:** @matbesancon
**Reviewers:** @ablaom
**Managing EiC:** Valentin Churavy

**Author instructions**

Thanks for submitting your paper to JCON @ppalmes. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @matbesancon.

@ppalmes if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #88 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by ppalmes** [comment]
@whedon commands

**Comment by ppalmes** [comment]
@whedon generate from branch master

**Comment by whedon** [comment]
PDF failed to compile for issue #88 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch juliacon2021. Reticulating splines etc...
```

**Comment by matbesancon** [comment]
seems the error is linked to a missing package now

**Comment by whedon** [comment]
PDF failed to compile for issue #88 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by ppalmes** [comment]
@whedon generate pdf from branch juliacon2021

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch juliacon2021. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #88 with the following error: 
```
 Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
===========Latexmk: Missing input file: 'subfigure.sty' from line
  '! LaTeX Error: File `subfigure.sty' not found.'
Latexmk: Missing input file: 'subfigure.sty' from line
  '! LaTeX Error: File `subfigure.sty' not found.'
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

```

**Comment by whedon** [comment]
PDF failed to compile for issue #88 with the following error: 
```
 Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.aux'
      'paper.out'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

```

**Comment by ppalmes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #88 with the following error: 
```
 Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.aux'
      'paper.out'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

```

**Comment by whedon** [comment]
PDF failed to compile for issue #88 with the following error: 
```
 Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.aux'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.out'
------------
Run number 3 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

```

**Comment by whedon** [comment]
PDF failed to compile for issue #88 with the following error: 
```
 Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.aux'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.out'
------------
Run number 3 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

```

**Comment by whedon** [comment]
PDF failed to compile for issue #88 with the following error: 
```
 Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.aux'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.out'
------------
Run number 3 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

```

**Comment by vchuravy** [comment]
@ppalmes you can use https://whedon.theoj.org/ to get access to the logs.

https://whedon.theoj.org/preview?id=1f1442aa9bb8bf86c6350bbb
```
Your paper failed to compile with the following errors:

Looks like we failed to compile the PDF with the following error: [WARNING] Could not load include file 'amlpcode' at line 225 column 19 [WARNING] Could not load include file 'amlpcode' at line 225 column 19 [WARNING] Could not load include file 'amlpcode' at line 225 column 19 [WARNING] Could not load include file 'amlpcode' at line 225 column 19 Error producing PDF. ! LaTeX Error: Can be used only in preamble. See the LaTeX manual or LaTeX Companion for explanation. Type H for immediate help. ... l.313 \documentclass 
```

**Comment by whedon** [comment]
PDF failed to compile for issue #88 with the following error: 
```
 Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.aux'
------------
Run number 2 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'paper.out'
------------
Run number 3 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -recorder  "paper.tex"'
------------
Failure to make 'paper.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'paper.log' for details
Looks like we failed to compile the PDF

```

**Comment by ppalmes** [comment]
@whedon generate pdf

**Comment by ppalmes** [comment]
thanks @ranjanan , that's the fix, a missing .latexmkrc.

**Comment by matbesancon** [comment]
thanks, we'll look for reviewers

**Comment by ppalmes** [comment]
@matbesancon, @ablaom : any update please?

**Comment by ablaom** [comment]
I have now read the manuscript but have not attempted to use the
software.

### Synopsis

A Julia software package called AMLP is described. This software
allows one to combine multiple pre-processing elements (categorical
encoders, dimension reducers, etc) with a supervised learner to
construct a new supervised learner pipeline, with a view to searching for
combinations that maximize a performance estimate. The individual
elements are models wrapped from scikit-learn or R. This architecture
searching tool is similar to existing tools (such as TPOT and AutoSk),
in the sense of what kind of architectures are possible. However, as a
Julia implementation, it appears to have advantages in terms of
usability and performance. 

I think this work and software is a valuable contribution and would be
of interest to the Julia community. I do have some concerns I
would like addressed before recommending publication:

#### Methodology for comparing frameworks

In section 3.2 (see especially Tables 2-7) AMLP is ranked, compared
with its competitors, on various datasets, according to the average
performance estimate `AvgErr`. As I understand it, no account is taken
of the *uncertainties* of these estimates, which means the rankings
are, by themselves not very useful (at least, as they apply to a
single dataset).

For example it may be that framework A is ranked ahead of framework B
on a given data set because A gets an `AvgErr` of 76, while B
scores 78. But if estimates for the associated standard errors are +/-
5.0, the difference is not statistically significant, and we should
rank both A and B the same (i.e., call a draw).

Perhaps some hypothesis test based face-off or similar would be more
meaningful? See for example [this
paper](https://link.springer.com/article/10.1007%2Fs10994-006-6226-1).

Perhaps I am missing something? Can the authors clarify this point?

#### Characterization of MLJ

The following characterization of the MLJ toolbox (Under "1.1 Related
Work") has never been true:

"However, [MLJ's] pipeline model only supports a linear non-branching chain of transformers and learners"

Since version 0.1, MLJ has allowed the user to build composite models
of considerably greater complexity than the pipelines constructible
using AMLP. To give two examples, one can construct, using MLJ's
generic composite model syntax, a Wolpert model stack (see
[here](https://github.com/ablaom/MachineLearningInJulia2020/blob/master/wow.ipynb))
and one can wrap supervised models with *learned* target
transformations (see
[here](https://alan-turing-institute.github.io/MLJ.jl/dev/composing_models/#Building-a-simple-learning-network)). Such
model composition features are explicated in [the
documentation](https://alan-turing-institute.github.io/MLJ.jl/dev/about_mlj/#Model-composability)
and in these two articles: [general
paper](https://doi.org/10.21105/joss.02704) and [model composition
paper](https://arxiv.org/abs/2012.15505).

Additionally, I find the following statement misleading:

"Also, [MLJ's] pipeline architecture does not support symbolic
expression for easy to understand pipeline composition similar to
AMLP."

It seems to me that MLJ's canned [`@pipeline`
macro](https://alan-turing-institute.github.io/MLJ.jl/dev/linear_pipelines/)
provides a way to construct some kinds of pipelines using a "symbolic
expression" that is "easy to understand". There isn't the `+` operator
for recombining "select-and-transform" operations (a nice feature) but
you can sometimes achieve the same results by modifying
hyperparameters of models that offer this functionality internally
(e.g., `ContinuousEncoder`).

**Comment by ppalmes** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00088/jcon.00088/10.21105.jcon.00088.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00088/jcon.00088/10.21105.jcon.00088.pdf) :page_facing_up: :point_left:

**Comment by ppalmes** [comment]
@matbesancon @ablaom @vchuravy 
I finally finished the edits based on the comments of @ablaom. Highly appreciate it if you can take a look and give advice if there are still things i missed based on the comments. 

Summary of changes:
- added significance testing. Tables include rank results and a sign of either =, >, < to represent if the rank performance is similar (draw) or significantly superior or significantly inferior with alpha=0.05 level of significance.
- remove the misleading statement about MLJ

Thanks for all your inputs.

Regards,
Paulito

**Comment by ablaom** [comment]
@matbesancon

Thanks @ppalmes for considering my comments.

 I'm happy with the changes and recommend publication.

**Comment by ppalmes** [comment]
Thanks @ablaom for the great suggestions to improve the quality of the paper.

**Comment by ppalmes** [comment]
@matbesancon @vchuravy, can you please take a look and give advice how to proceed? thanks!

**Comment by matbesancon** [comment]
@whedon accept

**Comment by whedon** [comment]
To recommend a paper to be accepted use `@whedon recommend-accept`

**Comment by matbesancon** [comment]
@whedon recommend-accept

**Comment by whedon** [comment]
I can't accept a paper that hasn't been reviewed!

**Comment by matbesancon** [comment]
@whedon start review
