### ISSUE TITLE
[REVIEW]: ReactiveMP.jl: A Julia Package for Reactive Message Passing-based Bayesian Inference

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#91]
**Submitting author:** @bvdmitri (<a href="http://orcid.org/0000-0001-9655-7986">Dmitry Bagaev</a>)
**Repository:** <a href="https://github.com/biaslab/ReactiveMP.jl" target ="_blank">https://github.com/biaslab/ReactiveMP.jl</a>
**Version:** v1.3.1
**Reviewer:** @ludgerpaehler, @torfjelde
**Archive:** <a href="https://doi.org/10.5281/zenodo.5913617" target="_blank">10.5281/zenodo.5913617</a>

## Status

[![status](https://proceedings.juliacon.org/papers/d3ea9d7a33de29ee7c74f38b3cd7b43c/status.svg)](https://proceedings.juliacon.org/papers/d3ea9d7a33de29ee7c74f38b3cd7b43c)

Status badge code:

```
HTML: <a href="https://proceedings.juliacon.org/papers/d3ea9d7a33de29ee7c74f38b3cd7b43c"><img src="https://proceedings.juliacon.org/papers/d3ea9d7a33de29ee7c74f38b3cd7b43c/status.svg"></a>
Markdown: [![status](https://proceedings.juliacon.org/papers/d3ea9d7a33de29ee7c74f38b3cd7b43c/status.svg)](https://proceedings.juliacon.org/papers/d3ea9d7a33de29ee7c74f38b3cd7b43c)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/biaslab/ReactiveMP.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ludgerpaehler & @torfjelde, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @matbesancon know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/biaslab/ReactiveMP.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Authorship:** Has the submitting author (@bvdmitri) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format

- [x] **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [x] **Page limit:** Is the page limit for extended abstracts respected by the submitted document?

### Content

- [x] **Context:** is the scientific context motivating the work correctly presented?
- [x] **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
- [x] **Results:** are the results presented and compared to approaches with similar goals?
### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/biaslab/ReactiveMP.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Authorship:** Has the submitting author (@bvdmitri) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format

- [x] **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [x] **Page limit:** Is the page limit for extended abstracts respected by the submitted document?

### Content

- [x] **Context:** is the scientific context motivating the work correctly presented?
- [x] **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
- [x] **Results:** are the results presented and compared to approaches with similar goals?

**Comment by whedon** [comment]
PDF failed to compile for issue #91 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by torfjelde** [comment]
@matbesancon I can't edit the checklist :confused:

**Comment by matbesancon** [comment]
I am not sure why this happens, you're the second one to have the issue. In the meantime, the hack @gdalle found was to copy the checklist to their own comment and edit it. Will let you know when we find a fix

**Comment by matbesancon** [comment]
for the invitation, it should be fine now since you are listed as one of the two reviewers

**Comment by torfjelde** [comment]
### Conflict of interest
* [ ]  As the reviewer I confirm that I have read the [JuliaCon conflict of interest policy](https://proceedings.juliacon.org/guide/authors#coi) and that there are no conflicts of interest for me to review this work.

### Code of Conduct
* [ ]  I confirm that I read and will adhere to the [JuliaCon code of conduct](https://proceedings.juliacon.org/coc).

### General checks
* [ ]  **Repository:** Is the source code for this software available at the [repository url](https://github.com/biaslab/ReactiveMP.jl)?
* [ ]  **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
* [ ]  **Authorship:** Has the submitting author (@bvdmitri) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality
* [ ]  **Installation:** Does installation proceed as outlined in the documentation?
* [ ]  **Functionality:** Have the functional claims of the software been confirmed?
* [ ]  **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation
* [ ]  **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
* [ ]  **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
* [ ]  **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
* [ ]  **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
* [ ]  **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
* [ ]  **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Paper format
* [ ]  **Authors:** Does the `paper.tex` file include a list of authors with their affiliations?
* [ ]  **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
* [ ]  **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
* [ ]  **Page limit:** Is the page limit for extended abstracts respected by the submitted document?

### Content
* [ ]  **Context:** is the scientific context motivating the work correctly presented?
* [ ]  **Methodology:** is the approach taken in the work justified, presented with enough details and reference to reproduce it?
* [ ]  **Results:** are the results presented and compared to approaches with similar goals?

**Comment by torfjelde** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #91 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by bvdmitri** [comment]
@whedon generate pdf from branch paper/julia_proceedings_2021

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper/julia_proceedings_2021. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00091/jcon.00091/10.21105.jcon.00091.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00091/jcon.00091/10.21105.jcon.00091.pdf) :page_facing_up: :point_left:

**Comment by torfjelde** [comment]
Ah thanks @bvdmitri ! But yeah, it's the same as the one I've been looking at, so np:)

**Comment by bvdmitri** [comment]
@torfjelde Ahh, I see, I missed your 'EDIT' comment. Cool!

**Comment by torfjelde** [comment]
Btw, I opened an issue in the repo regarding the benchmark comparison to Turing.jl. It doesn't make the claims in the paper incorrect (the perf-diff is still an the order of magnitudes on conjugate models), so no worries wrt. the paper submission :+1:

**Comment by bvdmitri** [comment]
Yes! I saw it and that is very useful! My laptop is in the office - I will definitely rerun these benchmarks tomorrow! I PM'ed you in Julia Slack regarding other models I use for benchmarking (they are not present in the main repository, but in my private one).

**Comment by torfjelde** [comment]
I've posted my full review above: https://github.com/JuliaCon/proceedings-review/issues/91#issuecomment-972963611.

**Comment by bvdmitri** [comment]
Dear @torfjelde , first of all thank you for reviewing our work! We appreciate your effort and time you spent on it.
I will just leave here a couple of remarks about your comments in https://github.com/JuliaCon/proceedings-review/issues/91#issuecomment-972963611 .

I do think we can improve both paper content and documentation a bit based on your comments.

> all existing factor graph frameworks [...] use preset message sequence schedules

This is an indeed quite a statement without a context. You correctly assumed that we meant "As far as the authors are aware". We can definitely change it in our final version.

> The comparison to a general-purpose PPL, e.g. Turing.jl, might give the impression that ReactiveMP.jl supports a larger family of models than it really does. Though it's good that the performance claim is limited to conjugate models:

Hm, that might be true. I'm not sure we explicitly outline somewhere in our documentation the scope of the package. This is due to the fact that `ReactiveMP.jl` is a successor of `ForneyLab.jl`. `ForneyLab.jl` does support inference in basically most of models that Turing.jl does with the help of nonlinear node and sampling. `ReactiveMP.jl` is supposed to be sort of `ForneyLab.jl 2.0`, but we didn't port and didn't reimplement all of the existing functionality from `ForneyLab.jl`. That is true that currently ReactiveMP.jl is limited to a specific family of models, namely conjugate state space models. More or less representative list of supported models (not all) can be found in `demo/` folder (but you've probably already seen it).

I think we could be more explicit here! I can change it in README and repo documentation. What would you prefer? Would like me to outline it in the paper content as well? It is not a problem :)

Regarding performance claims, we test only models we can test ¯\_(ツ)_/¯. Since in most of our models we use analytical solutions for messages and we do not use sampling I think we are guaranteed to be faster than sampling-based solutions (though it fallbacks again to the discussion that we do not support all models).

> In general, any valid snippet of Julia code can be used inside the @model block.

Ah, I see now that this statement might be a bit confusing. Here we mean that you can use `if` statements, `for` statements, you can define `lambda`-functions in your model etc.. For example `Soss.jl` does not allow `for` blocks. We did not want to imply that inference will run without any errors in this statement. We may change this to be more clear. 

> unless one has defined nodes for each of the operations present at the top-level

You understood it correctly. Package consists of a set of standard nodes and message computations rules. We are constantly adding new nodes and rules, but it takes some time :) Currently if something does not work you either get a "missing node" error or "missing rule". It does not necessarily mean that package cannot run inference at all, but maybe we just missed some rules or still looking for a time to implement it.

Package is very young in that sense. We have another PhD project that is aimed to expand the scope of the package to more models and reduce number of such "missing something" errors. We also have plans to integrate with Turing.jl and Soss.jl at some point. 

> Finally, though I recognize that this would probably require quite a bit of effort/time: it would be really awesome to have comparisons to other software based on message-passing from outside the Julia community, e.g. Infer.NET.

That is true, I actually have comparison with Infer.Net in my private repos. The problem here is that I'm not an expert in C# at all. In addition, model specifications in C# are huge - they don't have very nice `@macro` lambdas :).  I wrote a lot of code just for a setup and to make it look like in Julia and I'm not sure I did everything correct. Infer.NET gives reasonably performance btw (on models I managed to test), it is somewhere in between ReactiveMP and Turing.

Let me know what do you think and I will adjust the paper's content a bit. Thanks again for your time and comments!

**Comment by torfjelde** [comment]
> This is an indeed quite a statement without a context. You correctly assumed that we meant "As far as the authors are aware". We can definitely change it in our final version.

Perfect!

> Hm, that might be true. I'm not sure we explicitly outline somewhere in our documentation the scope of the package. This is due to the fact that ReactiveMP.jl is a successor of ForneyLab.jl. ForneyLab.jl does support inference in basically most of models that Turing.jl does with the help of nonlinear node and sampling. ReactiveMP.jl is supposed to be sort of ForneyLab.jl 2.0, but we didn't port and didn't reimplement all of the existing functionality from ForneyLab.jl. That is true that currently ReactiveMP.jl is limited to a specific family of models, namely conjugate state space models. More or less representative list of supported models (not all) can be found in demo/ folder (but you've probably already seen it).

> EDIT: Ah, we do mention it in our README, but not in the documentation. I will change it as well.

> I think we could be more explicit here! I can change it in README and repo documentation. What would you prefer? Would like me to outline it in the paper content as well? It is not a problem :)

Ah I missed the part in the README! And indeed, the statements in the README are exactly what I had in mind! And regarding the paper: as I mentioned above, just a brief sentence or even half a sentence about the restrictions ReactiveMP.jl would make the presentation even better. Something along the lines of "Even though ReactiveMP.jl does not currently have support for _all_ models supported by more general-purpose PPLs, for the ones we do have support the performance is superior" (not _exactly_ this statement, but you get the idea).

And because I feel the need to say this: I would say the exact same thing if Turing.jl wasn't even mentioned, e.g. if you were comparing to Stan instead. It's more just that for someone not super-familiar with the topic, reading the paper one could possibly walk away with the impression that "ReactiveMP.jl supports the same kind of models as Turing.jl/Stan, and ReactiveMP.jl is faster on conjugate models", and then a user installs ReactiveMP.jl and tries something rather trivial such as:

```julia
mymul(a, b) = a * b # or any user-defined function

@model function linear_gaussian_ssm_smoothing(n, A, B, P, Q)
    ...
    for t in 2:n
        x[t] ~ MvGaussianMeanCovariance(mymul(A, x[t - 1]), P)
        y[t] ~ MvGaussianMeanCovariance(mymul(B, x[t]), Q)    
    end

    return x, y
end
```

and then

```julia
model, vars = linear_gaussian_ssm_smoothing(n, A, B, P, Q);
```

results in

```
Unknown functional form 'mymul' used for node specification.

[...]
```

In contrast, in a general purpose PPL, e.g. Turing.jl or (AFAIK) Gen.jl, the above would _just work_. 

But, as I said, I'm probably overly sensitive to this because of my previous experience interacting with the community; I've often found myself saying "Ehh for this problem Turing.jl is probably not the right choice; you want something more specialized." (and I'll be sure to recommend ReactiveMP.jl for models such as Linear SSM in high-perf-required settings going forward) or people just being generally quite confused as to why there are so many PPLs in Julia because we're not being clear enough regarding our pros and cons, and so I find myself gravitating towards being a bit clearer regarding this. (We can also definitively do a better job of this in Turing.jl!)

> Regarding performance claims, we test only models we can test ¯_(ツ)_/¯. Since in most of our models we use analytical solutions for messages and we do not use sampling I think we are guaranteed to be faster than sampling-based solutions (though it fallbacks again to the discussion that we do not support all models).

I think you performance claims are completely fine! My previous comment was _endorsing_ the fact that you explicitly mention you're comparing conjugacy models:)

> Ah, I see now that this statement might be a bit confusing. Here we mean that you can use if statements, for statements, you can define lambda-functions in your model etc.. For example Soss.jl does not allow for blocks. We did not want to imply that inference will run without any errors in this statement. We may change this to be more clear.

Sounds good!

> Package is very young in that sense. We have another PhD project that is aimed to expand the scope of the package to more models and reduce number of such "missing something" errors. We also have plans to integrate with Turing.jl and Soss.jl at some point.

As mentioned in DMs, I'm very much looking forward to this!

> That is true, I actually have comparison with Infer.Net in my private repos. The problem here is that I'm not an expert in C# at all. In addition, model specifications in C# are huge - they don't have very nice @macro lambdas :). I wrote a lot of code just for a setup and to make it look like in Julia and I'm not sure I did everything correct. Infer.NET gives reasonably performance btw (on models I managed to test), it is somewhere in between ReactiveMP and Turing.

Yeah I figured this was probably the issue, hence why I said "though I realize this will be probably require a fair bit of effort". So this is completely fine!

**Comment by bvdmitri** [comment]
@whedon generate pdf from branch paper/julia_proceedings_2021

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper/julia_proceedings_2021. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00091/jcon.00091/10.21105.jcon.00091.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00091/jcon.00091/10.21105.jcon.00091.pdf) :page_facing_up: :point_left:

**Comment by bvdmitri** [comment]
@torfjelde I've update my paper based on your comments, you can quickly see changes here: [commit1](https://github.com/biaslab/ReactiveMP.jl/commit/77c786b982276c112b2ddedc31115948ec5539dd), [commit2](https://github.com/biaslab/ReactiveMP.jl/commit/35b298e25a30f09f0cad551ff99645ee7c740140).

**Comment by torfjelde** [comment]
@bvdmitri Excellent! Really like the changes you made:)

**Comment by bvdmitri** [comment]
@matbesancon 

Do we have any deadlines for JuliaCon2021 submission process? I would like to submit a full article about `ReactiveMP` (which goes very deep into details about reactive message passing and is very different from this submission) in the JMLR somewhere before January. They do have the following statement in their submission guide:

> Submissions to JMLR cannot have been published previously in any other journal. We will consider submissions that have been published at workshops or conferences. In these cases, we expect the JMLR submission to cite the prior work, go into much greater depth and to extend the published results in a substantive way.
...
We will also consider concurrent submissions of papers that are under review at conferences, provided the conference explicitly allows for this. 
...

So I either need to cite the prior work (which is this paper) or I need an explicit permission from JuliaCon 2021 Proceedings for a cross-review.

**Comment by ludgerpaehler** [comment]
@matbesancon @bvdmitri 

An excellent package, with exemplary documentation. In reviewing the individual checkpoints the only very minor "fault" I could find was with the README, and its equation rendering under GitHub's dark mode (which should be quite easy to fix I believe), i.e. see

https://github.com/biaslab/ReactiveMP.jl/issues/71

The paper is well written, but I would recommend the addition of a few articles at some points in the paper. Going through the points in the order of appearance in the paper:

In the abstract:
> ".. of variational family of distributions"  -> "of **the** variational family of distributions"

In section 2 *Message Passing*:
> ".. we exploit reactive programming approach" -> "we exploit **the** reactive programming approach.."

In section 3 *Reactive Message Passing*:
> "We present ReactiveMP.jl package .." -> "We present **the** ReactiveMP.jl package.."

> "In our experiments new implementation scales comfortably ..." -> "In our experiments **our/this** new implementation scales comfortably.."

> ", supports real-time data inference." -> ", **and** support real-time data inference"

> "Moreover, ReactiveMP.jl API supports various processing models..." -> "Moreover, ReactiveMP.jl's API supports various processing models.."

In section 4 *Conclusions* (this is more of a style suggestion):

I would recommend to consider switching the "that" for a "which" in the following sentence.
> We developed ReactiveMP.jl as a package that enables developers to builld ... -> We developed ReactiveMP.jl as a package which enables developers to build..


With the minor README rendering "issue" resolved and the non-style suggestions included, I would recommend direct acceptance to the proceedings.

**Comment by bvdmitri** [comment]
@ludgerpaehler thank you for your review! I adjusted text a bit based on your comments.

**Comment by bvdmitri** [comment]
@whedon generate pdf from branch paper/julia_proceedings_2021

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch paper/julia_proceedings_2021. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00091/jcon.00091/10.21105.jcon.00091.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00091/jcon.00091/10.21105.jcon.00091.pdf) :page_facing_up: :point_left:

**Comment by ludgerpaehler** [comment]
@matbesancon With the now included amendments, I would recommend direct acceptance.

**Comment by matbesancon** [comment]
@whedon check references

**Comment by matbesancon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon recommend-accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by matbesancon** [comment]
@whedon check references from from branch paper/julia_proceedings_2021

**Comment by whedon** [comment]
```
Attempting to check references... from custom branch paper/julia_proceedings_2021
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/141000671 is OK
- 10.3390/e23070807 is OK
- 10.1287/opre.38.5.911 is OK
- 10.1016/j.ijar.2018.11.002 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
No archive DOI set. Exiting...

**Comment by matbesancon** [comment]
@bvdmitri can you archive the repo on zenodo, precisely that corresponds to the version used in the paper

**Comment by bvdmitri** [comment]
@matbesancon We archived our repo on Zenodo here https://zenodo.org/record/5913617 . All statements in the paper are valid for the latest release too (we even improved our performance better and it became faster since the last JuliaCon).

**Comment by matbesancon** [comment]
@whedon set 10.5281/zenodo.5913617 as archive

**Comment by whedon** [comment]
OK. <a href="https://doi.org/10.5281/zenodo.5913617" target="_blank">10.5281/zenodo.5913617</a> is the archive.

**Comment by matbesancon** [comment]
@whedon set v1.3.1 as version

**Comment by whedon** [comment]
OK. v1.3.1 is the version.

**Comment by matbesancon** [comment]
@whedon recommend-accept from branch paper/julia_proceedings_2021

**Comment by whedon** [comment]
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/141000671 is OK
- 10.3390/e23070807 is OK
- 10.1287/opre.38.5.911 is OK
- 10.1016/j.ijar.2018.11.002 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment]
:wave: @JuliaCon/jcon-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/JuliaCon/proceedings-papers/pull/53

If the paper PDF and Crossref deposit XML look good in https://github.com/JuliaCon/proceedings-papers/pull/53, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch paper/julia_proceedings_2021 
```

**Comment by matbesancon** [comment]
@bvdmitri can you take a look at the paper produced and let us know if all good on your side?

**Comment by bvdmitri** [comment]
@matbesancon yeap, that what I was doing a couple of minutes ago. I didn't notice anything wrong, everything is good on my side. I think it is in a good shape! Thanks for your effort!

**Comment by matbesancon** [comment]
@whedon accept from branch paper/julia_proceedings_2021

**Comment by matbesancon** [comment]
@whedon accept

**Comment by vchuravy** [comment]
@whedon accept deposit=true from branch paper/julia_proceedings_2021

**Comment by whedon** [comment]
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment]
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JCON!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/JuliaCon/proceedings-papers/pull/54
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/jcon.00091](https://doi.org/10.21105/jcon.00091)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by whedon** [comment]
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://proceedings.juliacon.org/papers/10.21105/jcon.00091/status.svg)](https://doi.org/10.21105/jcon.00091)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/jcon.00091">
  <img src="https://proceedings.juliacon.org/papers/10.21105/jcon.00091/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://proceedings.juliacon.org/papers/10.21105/jcon.00091/status.svg
   :target: https://doi.org/10.21105/jcon.00091
```
This is how it will look in your documentation:

[![DOI](https://proceedings.juliacon.org/papers/10.21105/jcon.00091/status.svg)](https://doi.org/10.21105/jcon.00091)

**We need your help!**

JuliaCon Proceedings is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://forms.gle/yANMe4c9YmuW9MWcA
- Making a small donation to support our running costs here: https://numfocus.salsalabs.org/donate-to-jcon
